name: CI

on:
  push:
    branch: ["master"]
  pull_request:
    branch: ["master"]

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'

      - name: Run Golang Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59