name: CI

on:
  push:
    branch: ["master"]
  pull_request:
    branch: ["master"]

job:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'

      - name: Run Golang Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.0
          args: --timeout=10m